# Generated by Django 4.2.2 on 2023-06-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=40)),
                ('raw_material_name', models.CharField(max_length=40)),
                ('iron_concentration', models.FloatField()),
                ('silicon_concentration', models.FloatField()),
                ('aluminum_concentration', models.FloatField()),
                ('calcium_concentration', models.FloatField()),
                ('sulfur_concentration', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
